#PATH to all data
data_dir: /tmp/data

########## IMPORT DATA TO CONTENTFUL ##########

## EXPORTED XML FILE FROM WORDPRESS
wordpress_xml_path: wordpress_settings/wordpress.xml

## CONVERT CONTENTFUL MODEL TO CONTENTFUL IMPORT STRUCTURE
content_model_json: wordpress_settings/contentful_model.json
converted_model_dir: wordpress_settings/contentful_structure.json

contentful_structure_dir: wordpress_settings/default_contentful_structure.json

contentful_hero_template_id: "<hero_template_id>"
contentful_post_template_id: "<post_template_id>"

# Provide a csv file with columns id, categories and tags to modify the wordpress blog during import
wordpress_modify_csv: modify.csv

# If using a `modify csv`, skip importing posts that are not found in the csv
wordpress_modify_skip: true

# If using a `modify csv`, skip importing old tags/categories and only use the ones provided in the csv
wordpress_modify_skip_old_tags: false
wordpress_modify_skip_old_categories: false